[CmdletBinding()]
param([switch]$Check)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$Utf8NoBom = [System.Text.UTF8Encoding]::new($false)
$Root = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))
$CasesPath = Join-Path $Root 'fixtures\png\cases.json'
$OutputPath = Join-Path $Root 'modules\mb-image\png\generated_vectors.mbt'
$TestOutputPath = Join-Path $Root 'modules\mb-image\png\generated_vectors_test.mbt'
$ManifestPath = Join-Path $Root 'fixtures\manifest.json'
$cases = Get-Content -Raw -LiteralPath $CasesPath | ConvertFrom-Json

if ($cases.schema_version -ne '1.0.0' -or @($cases.cases).Count -lt 17) {
  throw 'PNG fixture schema is incomplete.'
}

$defaults = $cases.defaults
foreach ($field in @('preserve_opaque_metadata', 'limits_profile', 'budget_profile', 'immutable_caller_state')) {
  if ($null -eq $defaults.PSObject.Properties[$field]) { throw "PNG fixture default is missing: $field" }
}
$limitProfiles = @($cases.limits_profiles | ForEach-Object { [string]$_ })
$budgetProfiles = @($cases.budget_profiles | ForEach-Object { [string]$_ })

$seen = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
foreach ($case in $cases.cases) {
  if ([string]::IsNullOrWhiteSpace($case.id) -or -not $seen.Add([string]$case.id)) {
    throw "PNG case id is missing or duplicated: $($case.id)"
  }
  if ($case.bytes_hex -notmatch '^(?:[0-9a-fA-F]{2})+$') {
    throw "PNG case has non-byte hexadecimal input: $($case.id)"
  }
  if ([string]::IsNullOrWhiteSpace($case.expected) -or $case.expected -notmatch '^[a-z0-9-]+$') {
    throw "PNG case has invalid expected result: $($case.id)"
  }
  $limitsProfile = if ($null -eq $case.PSObject.Properties['limits_profile']) { [string]$defaults.limits_profile } else { [string]$case.limits_profile }
  $budgetProfile = if ($null -eq $case.PSObject.Properties['budget_profile']) { [string]$defaults.budget_profile } else { [string]$case.budget_profile }
  if ($limitProfiles -cnotcontains $limitsProfile) { throw "PNG case has unknown limits profile: $($case.id)" }
  if ($budgetProfiles -cnotcontains $budgetProfile) { throw "PNG case has unknown Budget profile: $($case.id)" }
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('// Generated by scripts/fixtures/Generate-PngStructuralVectors.ps1. Do not edit.')
$lines.Add('')
$lines.Add('///|')
$lines.Add('fn _generated_png_structural_cases() -> Array[(String, Bytes, String)] {')
$lines.Add('  [')
foreach ($case in $cases.cases) {
  $limitsProfile = if ($null -eq $case.PSObject.Properties['limits_profile']) { [string]$defaults.limits_profile } else { [string]$case.limits_profile }
  if ($limitsProfile -cne 'standard') { continue }
  $moonBytes = (([regex]::Matches([string]$case.bytes_hex, '..') | ForEach-Object { '\x' + $_.Value.ToLowerInvariant() }) -join '')
  $lines.Add(('    ("{0}", b"{1}", "{2}"),' -f $case.id, $moonBytes, $case.expected))
}
$lines.Add('  ]')
$lines.Add('}')
$lines.Add('')
$text = ($lines -join "`n") + "`n"

$testLines = [System.Collections.Generic.List[string]]::new()
$testLines.Add('// Generated by scripts/fixtures/Generate-PngStructuralVectors.ps1. Do not edit.')
$testLines.Add('')
$testLines.Add('///|')
$testLines.Add('fn _generated_png_public_cases() -> Array[(String, Bytes, String, Bool, String, String, Bool)] {')
$testLines.Add('  [')
foreach ($case in $cases.cases) {
  $moonBytes = (([regex]::Matches([string]$case.bytes_hex, '..') | ForEach-Object { '\x' + $_.Value.ToLowerInvariant() }) -join '')
  $preserve = if ($null -eq $case.PSObject.Properties['preserve_opaque_metadata']) { [bool]$defaults.preserve_opaque_metadata } else { [bool]$case.preserve_opaque_metadata }
  $limitsProfile = if ($null -eq $case.PSObject.Properties['limits_profile']) { [string]$defaults.limits_profile } else { [string]$case.limits_profile }
  $budgetProfile = if ($null -eq $case.PSObject.Properties['budget_profile']) { [string]$defaults.budget_profile } else { [string]$case.budget_profile }
  $immutable = if ($null -eq $case.PSObject.Properties['immutable_caller_state']) { [bool]$defaults.immutable_caller_state } else { [bool]$case.immutable_caller_state }
  $testLines.Add(('    ("{0}", b"{1}", "{2}", {3}, "{4}", "{5}", {6}),' -f $case.id, $moonBytes, $case.expected, $preserve.ToString().ToLowerInvariant(), $limitsProfile, $budgetProfile, $immutable.ToString().ToLowerInvariant()))
}
$testLines.Add('  ]')
$testLines.Add('}')
$testLines.Add('')
$testText = ($testLines -join "`n") + "`n"

$sha = [Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([System.IO.File]::ReadAllBytes($CasesPath))).ToLowerInvariant()
$manifest = Get-Content -Raw -LiteralPath $ManifestPath | ConvertFrom-Json
$record = @($manifest.records | Where-Object { $_.id -ceq 'png-structural-safety-vectors' })
if ($record.Count -ne 1) { throw 'PNG fixture manifest record is missing.' }
foreach ($field in @($manifest.required_record_fields)) {
  if ($null -eq $record[0].PSObject.Properties[$field] -or [string]::IsNullOrWhiteSpace([string]$record[0].$field)) {
    throw "PNG fixture manifest field is missing: $field"
  }
}
if ($record[0].path -cne 'fixtures/png/cases.json' -or
  $record[0].origin -cne 'generated' -or
  $record[0].license -cne 'Apache-2.0' -or
  $record[0].sha256 -cne $sha) {
  throw 'PNG fixture manifest identity or digest is stale.'
}

if ($Check) {
  if (-not (Test-Path -LiteralPath $OutputPath) -or
    ([System.IO.File]::ReadAllText($OutputPath, $Utf8NoBom).Replace("`r`n", "`n")) -cne $text) {
    throw "Generated artifact stale: $OutputPath"
  }
  if (-not (Test-Path -LiteralPath $TestOutputPath) -or
    ([System.IO.File]::ReadAllText($TestOutputPath, $Utf8NoBom).Replace("`r`n", "`n")) -cne $testText) {
    throw "Generated artifact stale: $TestOutputPath"
  }
} else {
  [System.IO.File]::WriteAllText($OutputPath, $text, $Utf8NoBom)
  [System.IO.File]::WriteAllText($TestOutputPath, $testText, $Utf8NoBom)
}
Write-Host 'PNG structural vector generation/check passed.'
