[CmdletBinding()]
param([switch]$Check)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$Utf8NoBom = [System.Text.UTF8Encoding]::new($false)
$Root = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))
$CasesPath = Join-Path $Root 'fixtures\png\cases.json'
$OutputPath = Join-Path $Root 'modules\mb-image\png\generated_vectors.mbt'
$ManifestPath = Join-Path $Root 'fixtures\manifest.json'
$cases = Get-Content -Raw -LiteralPath $CasesPath | ConvertFrom-Json
if ($cases.schema_version -ne '1.0.0' -or @($cases.cases).Count -lt 5) { throw 'PNG fixture schema is incomplete.' }
foreach ($case in $cases.cases) {
  if ([string]::IsNullOrWhiteSpace($case.id) -or $case.bytes_hex -notmatch '^[0-9a-fA-F]+$' -or [string]::IsNullOrWhiteSpace($case.expected)) { throw "Invalid PNG case: $($case.id)" }
}
$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('// Generated by scripts/fixtures/Generate-PngStructuralVectors.ps1. Do not edit.')
$lines.Add('')
$lines.Add('///|')
$lines.Add('fn _generated_png_structural_case_ids() -> Array[String] {')
$lines.Add('  [')
foreach ($case in $cases.cases) { $lines.Add(('    "{0}",' -f $case.id)) }
$lines.Add('  ]')
$lines.Add('}')
$lines.Add('')
$text = ($lines -join "`n") + "`n"
if ($Check) {
  if (-not (Test-Path -LiteralPath $OutputPath) -or ([System.IO.File]::ReadAllText($OutputPath, $Utf8NoBom).Replace("`r`n", "`n")) -cne $text) { throw "Generated artifact stale: $OutputPath" }
} else { [System.IO.File]::WriteAllText($OutputPath, $text, $Utf8NoBom) }
$sha = [Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([System.IO.File]::ReadAllBytes($CasesPath))).ToLowerInvariant()
$manifest = Get-Content -Raw -LiteralPath $ManifestPath | ConvertFrom-Json
$record = @($manifest.records | Where-Object { $_.id -ceq 'png-structural-safety-vectors' })
if ($record.Count -ne 1) { throw 'PNG fixture manifest record is missing.' }
foreach ($field in @($manifest.required_record_fields)) { if ($null -eq $record[0].PSObject.Properties[$field] -or [string]::IsNullOrWhiteSpace([string]$record[0].$field)) { throw "PNG fixture manifest field is missing: $field" } }
if ($record[0].path -cne 'fixtures/png/cases.json' -or $record[0].origin -cne 'generated' -or $record[0].sha256 -cne $sha) { throw 'PNG fixture manifest identity or digest is stale.' }
Write-Host 'PNG structural vector generation/check passed.'
