[CmdletBinding()]
param([switch]$Check)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$Utf8NoBom = [System.Text.UTF8Encoding]::new($false)
$Root = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))
$CasesPath = Join-Path $Root 'fixtures\qoi\cases.json'
$OutputPath = Join-Path $Root 'modules\mb-image\qoi\generated_vectors.mbt'
$ManifestPath = Join-Path $Root 'fixtures\manifest.json'

function Bytes-Literal([string]$Hex) {
  $clean = $Hex.Replace(' ', '')
  if (($clean.Length % 2) -ne 0) { throw "Odd payload hex length: $Hex" }
  $parts = for ($i = 0; $i -lt $clean.Length; $i += 2) { '\x' + $clean.Substring($i, 2).ToLowerInvariant() }
  return 'b"' + ($parts -join '') + '"'
}
function Bytes-Equal([byte[]]$Left, [byte[]]$Right) {
  if ($Left.Length -ne $Right.Length) { return $false }
  for ($i = 0; $i -lt $Left.Length; $i++) { if ($Left[$i] -ne $Right[$i]) { return $false } }
  return $true
}
function Write-Or-Check([string]$Path, [string]$Text) {
  $expected = $Utf8NoBom.GetBytes($Text)
  if ($Check) {
    if (-not (Test-Path -LiteralPath $Path)) { throw "Generated artifact missing: $Path" }
    $actual = [System.IO.File]::ReadAllBytes($Path)
    if (-not (Bytes-Equal $actual $expected)) { throw "Generated artifact stale: $Path" }
  } else {
    [System.IO.File]::WriteAllBytes($Path, $expected)
  }
}
function Format-Moon([string]$Text) {
  $temporary = Join-Path $Root 'modules\mb-image\qoi\generated_vectors.format.mbt'
  try {
    [System.IO.File]::WriteAllBytes($temporary, $Utf8NoBom.GetBytes($Text))
    & moon fmt $temporary | Out-Null
    if ($LASTEXITCODE -ne 0) { throw 'moon fmt failed for generated QOI vectors.' }
    return [System.IO.File]::ReadAllText($temporary, $Utf8NoBom)
  } finally {
    Remove-Item -LiteralPath $temporary -Force -ErrorAction SilentlyContinue
  }
}
function Expected-Hex([object]$Case) {
  if ($null -ne $Case.PSObject.Properties['pixels_hex']) { return [string]$Case.pixels_hex }
  $result = ''
  for ($i = 0; $i -lt [int]$Case.repeat; $i++) { $result += [string]$Case.expected_repeat_hex }
  return $result
}

$data = Get-Content -Raw -LiteralPath $CasesPath | ConvertFrom-Json
$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('// Generated by scripts/fixtures/Generate-QoiVectors.ps1. Do not edit.')
$lines.Add('')
$lines.Add('///|')
$lines.Add('fn _generated_qoi_cases() -> Array[(String, Bytes, Bytes, UInt64, UInt64, UInt64, UInt64)] {')
$lines.Add('  [')
foreach ($case in $data.valid_cases) {
  $lines.Add(('    ("{0}", {1}, {2}, {3}UL, {4}UL, {5}UL, {6}UL),' -f $case.id, (Bytes-Literal ([string]$case.stream_hex)), (Bytes-Literal (Expected-Hex $case)), $case.width, $case.height, $case.channels, $case.colorspace))
}
$lines.Add('  ]')
$lines.Add('}')
$lines.Add('')
$lines.Add('///|')
$lines.Add('fn _generated_qoi_adversarial_ids() -> Array[String] {')
$ids = (@($data.adversarial_cases) | ForEach-Object { '"' + $_.id + '"' }) -join ', '
$lines.Add("  [$ids]")
$lines.Add('}')
$lines.Add('')
$lines.Add('///|')
$lines.Add('fn _generated_qoi_chunk_schedules() -> Array[(String, Array[UInt64])] {')
$lines.Add('  [')
foreach ($schedule in $data.chunk_schedules) {
  $chunks = (@($schedule.chunks) | ForEach-Object { "${_}UL" }) -join ', '
  $lines.Add(('    ("{0}", [{1}]),' -f $schedule.id, $chunks))
}
$lines.Add('  ]')
$lines.Add('}')
$moon = Format-Moon (($lines -join "`n") + "`n")
Write-Or-Check $OutputPath $moon

$caseBytes = [System.IO.File]::ReadAllBytes($CasesPath)
$digest = [Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($caseBytes)).ToLowerInvariant()
$manifest = Get-Content -Raw -LiteralPath $ManifestPath | ConvertFrom-Json
$record = [ordered]@{
  id='qoi-1.0-conformance-vectors'; path='fixtures/qoi/cases.json'; origin='generated'
  source='https://qoiformat.org/qoi-specification.pdf (QOI 1.0, 2022-01-05) plus repository-derived adversarial schedules'
  author='MoonBit Native Foundation project generator'; retrieval_date='2026-07-20'; sha256=$digest
  license='Apache-2.0'; redistribution_status='not-applicable'
  expected_use='QOI-01, QOI-02, and QOI-04 portable QOI 1.0 canonical, adversarial, and forward-reader conformance'
}
$colorIds = @('color-srgb-reference-vectors', 'color-derived-edge-vectors')
$records = @($manifest.records | Where-Object { $_.id -cne $record.id -and $_.id -cnotin $colorIds }) + @($record) + @($manifest.records | Where-Object { $_.id -cin $colorIds })
$ordered = [ordered]@{
  schema_version=$manifest.schema_version; preferred_origin=$manifest.preferred_origin
  required_record_fields=@($manifest.required_record_fields); allowed_origins=@($manifest.allowed_origins)
  allowed_redistribution_statuses=@($manifest.allowed_redistribution_statuses)
  external_requires_confirmed_redistribution=$manifest.external_requires_confirmed_redistribution
  records=$records
}
$manifestText = (($ordered | ConvertTo-Json -Depth 20).Replace("`r`n", "`n").TrimEnd() + "`n")
Write-Or-Check $ManifestPath $manifestText
Write-Host 'QOI vector generation/check passed.'
